/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-1",
  aws_appsync_graphqlEndpoint:
    "https://dul7gbxqgvbfhk5ds3di5bfgwa.appsync-api.us-west-1.amazonaws.com/graphql",
  aws_appsync_region: "us-west-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-him5qoqcunexbeubalpuhhrpvy",
  aws_dynamodb_all_tables_region: "us-west-1",
  aws_dynamodb_table_schemas: [
    {
      tableName: "dynamoed81fa11-dev",
      region: "us-west-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "us-west-1:28d70658-88cd-44a6-ba9c-f350d364d4db",
  aws_cognito_region: "us-west-1",
  aws_user_pools_id: "us-west-1_UKK1oU5lG",
  aws_user_pools_web_client_id: "3n4sislkrbka8l0k44tuivib4e",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
